import Head from "next/head";
import Link from "next/link";
// import SignIn from "~/components/SignIn"
import { 
  useSession, 
  // signIn, signOut 
} from "next-auth/react";
import { ApplyBaseLayout  }from "~/components/layout/BaseLayout";
import type { ReactElement } from "react";

export default function Home() {
  const {data: session, status} = useSession();

  return (
    <>
      <Head>
        <title>Welcome - Anon Vendor POS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1>Welcome to <span>Anon Vendor POS</span></h1>
          {status === "unauthenticated" && <Link href={'/auth/signin'}>Please signin to continue</Link>}
          {status === "loading" && <p>Identifying recent login...</p>}
          {status === "authenticated" && <Link href={'/dashboard'}>Go to dashboard</Link>}
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return ApplyBaseLayout(page);
};